version: '3.7'

services:
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=taxi
      - POSTGRES_PASSWORD=taxi
      - POSTGRES_DB=taxi
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

volumes:
  postgres_data:
